name: Python add testing

on: [push]

jobs:
  build:
    runs-on: self-hosted
    # runs-on: ubuntu-latest
    # ubuntu container image will be used for executions
    # This is a GitHub-hosted Runner. We are not using any runners here.

    strategy:
      matrix:
        python-version: [3.8, 3.9]
        # After setting up the container, set the python env with 3.8 and 3.9. It will test in two different versions of python 
    # Above is the env
    # Steps are like stages in Jenkins, where we will have build, deploy and test stage, 
    steps:
    - uses: actions/checkout@v3
      # actions/checkout@v3 means it is a version 3 plug-in of checkout. 
    - name: Set up python
      uses: actions/setup-python@v2
      # actions/checkout@v3 means it is a version 2 plug-in of Python. 
      # Limited number of plugins
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
